### ISSUE TITLE
Database is temporarily locked error

### ISSUE THREAD

**Issue by icehuntman** [elkorol/addtionalFilesDeleter#1]
is this a working version? When I use it, I get an error after a few seconds of working properly

```
ERRO[2024-04-20 14:04:49] [Plugin / Addtional Files Deleter] Traceback (most recent call last): 
ERRO[2024-04-20 14:04:49] [Plugin / Addtional Files Deleter]   File "/root/.stash/plugins/community/additionalFilesDeleter/deleter.py", line 3, in <module> 
ERRO[2024-04-20 14:04:49] [Plugin / Addtional Files Deleter]     import stashapi.log as log 
ERRO[2024-04-20 14:04:49] [Plugin / Addtional Files Deleter] ModuleNotFoundError: No module named 'stashapi' 
ERRO[2024-04-20 14:04:49] Plugin returned error: exit status 1         
ERRO[2024-04-20 14:06:34] sceneUpdate: input: sceneUpdate updating scenes: executing `UPDATE `scenes` SET `updated_at`=? WHERE (`scenes`.`id` = ?)` [[2024-04-20T14:06:34+02:00 19194]]: database is locked 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter] DATABASE_LOCKED: updating scenes: executing `UPDATE `scenes` SET `updated_at`=? WHERE (`scenes`.`id` = ?)` [[2024-04-20T14:06:34+02:00 19194]]: database is locked ['sceneUpdate'] 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter] Database is temporarily locked. 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter] 200 OK query failed. v0.25.1-20-g157b2e7b 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter] Traceback (most recent call last): 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]   File "/root/.stash/plugins/community/additionalFilesDeleter/deleter.py", line 215, in <module> 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]     main() 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]   File "/root/.stash/plugins/community/additionalFilesDeleter/deleter.py", line 48, in main 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]     scenes_delete_record_paths() 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]   File "/root/.stash/plugins/community/additionalFilesDeleter/deleter.py", line 207, in scenes_delete_record_paths 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]     update = update_scene(scene_id, paths) 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]   File "/root/.stash/plugins/community/additionalFilesDeleter/deleter.py", line 56, in update_scene 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]     update = stash.update_scene( 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]              ^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]   File "/root/.local/lib/python3.11/site-packages/stashapi/stashapp.py", line 1467, in update_scene 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]     result = self._callGraphQL(query, variables) 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]   File "/root/.local/lib/python3.11/site-packages/stashapi/classes.py", line 233, in _callGraphQL 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]     return self._handleGQLResponse(response) 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]   File "/root/.local/lib/python3.11/site-packages/stashapi/classes.py", line 279, in _handleGQLResponse 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter]     raise Exception(error_msg) 
ERRO[2024-04-20 14:06:34] [Plugin / Addtional Files Deleter] Exception: 200 OK query failed. v0.25.1-20-g157b2e7b 
ERRO[2024-04-20 14:06:35] Plugin returned error: exit status 1         
ERRO[2024-04-20 14:10:32] sceneUpdate: input: sceneUpdate updating scenes: executing `UPDATE `scenes` SET `updated_at`=? WHERE (`scenes`.`id` = ?)` [[2024-04-20T14:10:32+02:00 23953]]: database is locked 
ERRO[2024-04-20 14:10:32] [Plugin / Addtional Files Deleter] DATABASE_LOCKED: updating scenes: executing `UPDATE `scenes` SET `updated_at`=? WHERE (`scenes`.`id` = ?)` [[2024-04-20T14:10:32+02:00 23953]]: database is locked ['sceneUpdate'] 
ERRO[2024-04-20 14:10:32] [Plugin / Addtional Files Deleter] Database is temporarily locked. 
ERRO[2024-04-20 14:10:32] [Plugin / Addtional Files Deleter] 200 OK query failed. v0.25.1-20-g157b2e7b 
```

**Comment by elkorol** [comment]
Works fine on my end, are you performing other tasks or front end scene mutations etc that might be causing the db to lock?
